[package]
name = "api-gateway"
description = "the central API gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-component = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true }
