spin_manifest_version = 2

[application]
name = "api-gateway"
version = "0.1.0"
authors = ["Kai Walter <kai.walter@outlook.de>"]
description = ""

[[trigger.http]]
route = "/..."
component = "api-gateway"

[component.api-gateway]
source = "target/wasm32-wasip1/release/api_gateway.wasm"
allowed_outbound_hosts = []
[component.api-gateway.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.api-gateway.dependencies]
"component:api1/data-handler" = { path = "../target/wasm32-unknown-unknown/debug/api1.wasm" }
