[workspace]
members = ["api-gateway","api1"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
spin-sdk = "3.0.1"
wit-bindgen = "0.43.0"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true