// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package httphandler represents the imported interface "gateway:api/http-handler".
package httphandler

import (
	"go.bytecodealliance.org/cm"
)

// APIRequest represents the record "gateway:api/http-handler#api-request".
//
//	record api-request {
//		method: string,
//		host: string,
//		path: string,
//		query: string,
//		headers: list<tuple<string, string>>,
//		body: option<list<u8>>,
//	}
type APIRequest struct {
	_       cm.HostLayout             `json:"-"`
	Method  string                    `json:"method"`
	Host    string                    `json:"host"`
	Path    string                    `json:"path"`
	Query   string                    `json:"query"`
	Headers cm.List[[2]string]        `json:"headers"`
	Body    cm.Option[cm.List[uint8]] `json:"body"`
}

// APIResponse represents the record "gateway:api/http-handler#api-response".
//
//	record api-response {
//		status: u16,
//		headers: list<tuple<string, string>>,
//		body: option<list<u8>>,
//	}
type APIResponse struct {
	_       cm.HostLayout             `json:"-"`
	Status  uint16                    `json:"status"`
	Headers cm.List[[2]string]        `json:"headers"`
	Body    cm.Option[cm.List[uint8]] `json:"body"`
}
