// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	httphandler "api-go/bindings/gateway/api/http-handler"
	"go.bytecodealliance.org/cm"
)

func lower_OptionListU8(v cm.Option[cm.List[uint8]]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerList(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_APIRequest(v httphandler.APIRequest) (f0 *uint8, f1 uint32, f2 *uint8, f3 uint32, f4 *uint8, f5 uint32, f6 *uint8, f7 uint32, f8 *[2]string, f9 uint32, f10 uint32, f11 *uint8, f12 uint32) {
	f0, f1 = cm.LowerString(v.Method)
	f2, f3 = cm.LowerString(v.Host)
	f4, f5 = cm.LowerString(v.Path)
	f6, f7 = cm.LowerString(v.Query)
	f8, f9 = cm.LowerList(v.Headers)
	f10, f11, f12 = lower_OptionListU8(v.Body)
	return
}
