// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "host".
package host

import (
	httphandler "api-go/bindings/gateway/api/http-handler"
)

// APIRequest represents the type alias "host#api-request".
//
// See [httphandler.APIRequest] for more information.
type APIRequest = httphandler.APIRequest

// APIResponse represents the type alias "host#api-response".
//
// See [httphandler.APIResponse] for more information.
type APIResponse = httphandler.APIResponse

// HostAPIRequest represents the imported function "host-api-request".
//
//	host-api-request: func(request: api-request) -> api-response
//
//go:nosplit
func HostAPIRequest(request APIRequest) (result APIResponse) {
	request0, request1, request2, request3, request4, request5, request6, request7, request8, request9, request10, request11, request12 := lower_APIRequest(request)
	wasmimport_HostAPIRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3), (*uint8)(request4), (uint32)(request5), (*uint8)(request6), (uint32)(request7), (*[2]string)(request8), (uint32)(request9), (uint32)(request10), (*uint8)(request11), (uint32)(request12), &result)
	return
}
