// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

// This file contains wasmimport and wasmexport declarations for "gateway:api".

//go:wasmimport host host-api-request
//go:noescape
func wasmimport_HostAPIRequest(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32, request4 *uint8, request5 uint32, request6 *uint8, request7 uint32, request8 *[2]string, request9 uint32, request10 uint32, request11 *uint8, request12 uint32, result *APIResponse)
