package component:api1;

interface data-handler {
  // The function to pass on the API request to.
  handle-data: func(key: api-request) -> api-request;

  // The API request record, aka. the object to pass between the two components.
  record api-request {
    name: string,
    steps: u32,
    processed: option<bool>,
  }
}

world api {
  export data-handler;
}
