// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

import (
	httphandler "api-go/bindings/gateway/api/http-handler"
	"go.bytecodealliance.org/cm"
)

func lift_OptionListU8(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[cm.List[uint8]]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[cm.List[uint8]])(cm.Some[cm.List[uint8]](cm.LiftList[cm.List[uint8]]((*uint8)(f1), (uint32)(f2))))
}

func lift_APIRequest(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32, f4 *uint8, f5 uint32, f6 *uint8, f7 uint32, f8 *[2]string, f9 uint32, f10 uint32, f11 *uint8, f12 uint32) (v httphandler.APIRequest) {
	v.Method = cm.LiftString[string](f0, f1)
	v.Host = cm.LiftString[string](f2, f3)
	v.Path = cm.LiftString[string](f4, f5)
	v.Query = cm.LiftString[string](f6, f7)
	v.Headers = cm.LiftList[cm.List[[2]string]](f8, f9)
	v.Body = lift_OptionListU8(f10, f11, f12)
	return
}

func lift_APIResponse(f0 uint32, f1 *[2]string, f2 uint32, f3 uint32, f4 *uint8, f5 uint32) (v httphandler.APIResponse) {
	v.Status = (uint16)(f0)
	v.Headers = cm.LiftList[cm.List[[2]string]](f1, f2)
	v.Body = lift_OptionListU8(f3, f4, f5)
	return
}
