// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package guest represents the exported interface "guest".
package guest

import (
	httphandler "api-go/bindings/gateway/api/http-handler"
)

// APIRequest represents the type alias "guest#api-request".
//
// See [httphandler.APIRequest] for more information.
type APIRequest = httphandler.APIRequest

// APIResponse represents the type alias "guest#api-response".
//
// See [httphandler.APIResponse] for more information.
type APIResponse = httphandler.APIResponse
