// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

// Exports represents the caller-defined exports from "guest".
var Exports struct {
	// HandleAPIRequest represents the caller-defined, exported function "handle-api-request".
	//
	//	handle-api-request: func(request: api-request) -> api-request
	HandleAPIRequest func(request APIRequest) (result APIRequest)

	// HandleAPIResponse represents the caller-defined, exported function "handle-api-response".
	//
	//	handle-api-response: func(request: api-response) -> api-response
	HandleAPIResponse func(request APIResponse) (result APIResponse)
}
