// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

// This file contains wasmimport and wasmexport declarations for "gateway:api".

//go:wasmexport guest#handle-api-request
//export guest#handle-api-request
func wasmexport_HandleAPIRequest(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32, request4 *uint8, request5 uint32, request6 *uint8, request7 uint32, request8 *[2]string, request9 uint32, request10 uint32, request11 *uint8, request12 uint32) (result *APIRequest) {
	request := lift_APIRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3), (*uint8)(request4), (uint32)(request5), (*uint8)(request6), (uint32)(request7), (*[2]string)(request8), (uint32)(request9), (uint32)(request10), (*uint8)(request11), (uint32)(request12))
	result_ := Exports.HandleAPIRequest(request)
	result = &result_
	return
}

//go:wasmexport guest#handle-api-response
//export guest#handle-api-response
func wasmexport_HandleAPIResponse(request0 uint32, request1 *[2]string, request2 uint32, request3 uint32, request4 *uint8, request5 uint32) (result *APIResponse) {
	request := lift_APIResponse((uint32)(request0), (*[2]string)(request1), (uint32)(request2), (uint32)(request3), (*uint8)(request4), (uint32)(request5))
	result_ := Exports.HandleAPIResponse(request)
	result = &result_
	return
}
